<?php

namespace App\Models;

use App\Enums\PMS\InstallmentPaymentMethod;
use App\Enums\PMS\InstallmentPaymentStatus;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\Activitylog\Models\Concerns\LogsActivity;
use Spatie\Activitylog\Support\LogOptions;

/**
 * One scheduled rent payment on a Lease, carrying its own tax-invoice
 * fields (TRNs, serial, date of supply) — generated by
 * `InstallmentGenerator`, transitioned by `PaymentService`.
 *
 * @method static where(string $string, InstallmentPaymentStatus $OVERDUE)
 */
class Installment extends Model
{
    use HasFactory;
    use LogsActivity;

    protected $fillable = [
        'lease_id',
        'is_security_deposit',
        'is_vat_only',
        'due_date',
        'grace_period_expiry_date',
        'net_amount',
        'vat_amount',
        'total_due_amount',
        'admin_penalty_amount',
        'paid_amount',
        'balance_due',
        'payment_method',
        'payment_status',
        'transaction_reference',
        'bank_name',
        'paid_date',
        'landlord_trn',
        'tenant_trn',
        'tax_invoice_serial',
        'date_of_supply',
        'vat_rate',
    ];

    protected $casts = [
        'is_security_deposit' => 'boolean',
        'is_vat_only' => 'boolean',
        'due_date' => 'date',
        'grace_period_expiry_date' => 'date',
        'net_amount' => 'decimal:2',
        'vat_amount' => 'decimal:2',
        'total_due_amount' => 'decimal:2',
        'admin_penalty_amount' => 'decimal:2',
        'paid_amount' => 'decimal:2',
        'balance_due' => 'decimal:2',
        'payment_method' => InstallmentPaymentMethod::class,
        'payment_status' => InstallmentPaymentStatus::class,
        'paid_date' => 'date',
        'date_of_supply' => 'date',
        'vat_rate' => 'decimal:4',
    ];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logAll();
    }

    /**
     * @return BelongsTo<Lease, $this>
     */
    public function lease(): BelongsTo
    {
        return $this->belongsTo(Lease::class);
    }

    /**
     * @return HasMany<InstallmentPayment, $this>
     */
    public function payments(): HasMany
    {
        return $this->hasMany(InstallmentPayment::class);
    }

    public function isPaid(): bool
    {
        return $this->getAttribute('payment_status') === InstallmentPaymentStatus::PAID;
    }

    public function isOverdue(): bool
    {
        return $this->getAttribute('payment_status') === InstallmentPaymentStatus::OVERDUE;
    }

    /**
     * Whether this installment has fallen past its own grace period without
     * being settled — the exact rule `pms:flag-overdue-installments` acts on.
     */
    public function isPastGracePeriod(): bool
    {
        if (in_array($this->getAttribute('payment_status'), [InstallmentPaymentStatus::PAID], true)) {
            return false;
        }

        $expiry = $this->getAttribute('grace_period_expiry_date');

        return $expiry !== null && $expiry->isPast();
    }
}
